package view;

import view.KorisnickiRacunView;
import model.KorisnickiRacunModel;
import model.KorisnikModel;
import controller.Controller;
import model.BankovniRacunModel;
import model.TransakcijaModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lukab
 */
public class KorisnikView extends javax.swing.JFrame {

    private KorisnikModel k_model;
    private KorisnickiRacunModel kr_model;
    private BankovniRacunModel br_model;
    private TransakcijaModel t_model;
    private Controller controller;
    private KorisnickiRacunView kr_view;

    /**
     * Creates new form Korisnik
     */
    public KorisnikView(KorisnickiRacunModel kr_model, KorisnikModel k_model) {
        initComponents();
        this.kr_model = kr_model;
        this.k_model = k_model;
        this.controller = new Controller(k_model, kr_model, br_model, t_model, kr_view);

        this.controller.prikazPodataka();

        this.ime.setText(this.k_model.getIme());
        this.prezime.setText(this.k_model.getPrezime());
        this.oib.setText(this.k_model.getOIB());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ime = new javax.swing.JLabel();
        prezime = new javax.swing.JLabel();
        oib = new javax.swing.JLabel();
        bankovniRacunButton = new javax.swing.JButton();
        odjavaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ime.setText("Ime");

        prezime.setText("Prezime");

        oib.setText("OIB");

        bankovniRacunButton.setText("Bankovni racun");
        bankovniRacunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankovniRacunButtonActionPerformed(evt);
            }
        });

        odjavaButton.setText("Odjava");
        odjavaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odjavaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oib)
                    .addComponent(prezime)
                    .addComponent(ime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(odjavaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bankovniRacunButton)
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(odjavaButton)
                .addGap(8, 8, 8)
                .addComponent(ime)
                .addGap(18, 18, 18)
                .addComponent(prezime)
                .addGap(18, 18, 18)
                .addComponent(oib)
                .addGap(41, 41, 41)
                .addComponent(bankovniRacunButton)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void odjavaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odjavaButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new KorisnickiRacunView().setVisible(true);
    }//GEN-LAST:event_odjavaButtonActionPerformed

    private void bankovniRacunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankovniRacunButtonActionPerformed
        // TODO add your handling code here:
        new BankovniRacunView(k_model, this, kr_model).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bankovniRacunButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KorisnikView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KorisnikView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KorisnikView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KorisnikView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Korisnik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bankovniRacunButton;
    private javax.swing.JLabel ime;
    private javax.swing.JButton odjavaButton;
    private javax.swing.JLabel oib;
    private javax.swing.JLabel prezime;
    // End of variables declaration//GEN-END:variables
}
