/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BankovniRacunModel;
import model.KorisnickiRacunModel;
import model.KorisnikModel;
import model.TransakcijaModel;

/**
 *
 * @author lukab
 */
public class TransakcijaView extends javax.swing.JFrame {
    
    private TransakcijaModel t_model;
    private BankovniRacunView br_view;
    private BankovniRacunModel br_model;
    private KorisnikModel k_model;
    private KorisnickiRacunModel kr_model;
    private KorisnickiRacunView kr_view;
    private Controller controller;

    /**
     * Creates new form TransakcijaView
     */
    public TransakcijaView(TransakcijaModel t_model, BankovniRacunView br_view, BankovniRacunModel br_model) {
        initComponents();
        this.t_model = t_model;
        this.br_view = br_view;
        this.br_model = br_model;
        
        this.controller = new Controller(k_model, kr_model, br_model, t_model, kr_view);
        
        this.controller.prikazTransakcija(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        povratakButton = new javax.swing.JButton();
        prikazUplate = new javax.swing.JButton();
        prikazIsplate = new javax.swing.JButton();
        prikazButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Datum transakcije", "Vrsta transakcije", "Kolicina transakcije", "Racun uplate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        povratakButton.setText("Povratak");
        povratakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                povratakButtonActionPerformed(evt);
            }
        });

        prikazUplate.setText("Uplate");
        prikazUplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikazUplateActionPerformed(evt);
            }
        });

        prikazIsplate.setText("Isplate");
        prikazIsplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikazIsplateActionPerformed(evt);
            }
        });

        prikazButton.setText("Prikazi sve");
        prikazButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikazButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(povratakButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prikazUplate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prikazIsplate))))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prikazButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(povratakButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prikazUplate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prikazIsplate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prikazButton)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void povratakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_povratakButtonActionPerformed
        // TODO add your handling code here:
        this.br_view.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_povratakButtonActionPerformed

    private void prikazUplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikazUplateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) this.jTable1.getModel();
        while (this.jTable1.getRowCount() > 0) {
            dm.removeRow(0);
        }
        
        this.controller.prikazUplate(jTable1);
    }//GEN-LAST:event_prikazUplateActionPerformed

    private void prikazIsplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikazIsplateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) this.jTable1.getModel();
        while (this.jTable1.getRowCount() > 0) {
            dm.removeRow(0);
        }
        this.controller.prikazIsplate(jTable1);
    }//GEN-LAST:event_prikazIsplateActionPerformed

    private void prikazButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikazButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) this.jTable1.getModel();
        while (this.jTable1.getRowCount() > 0) {
            dm.removeRow(0);
        }
        
        this.controller.prikazTransakcija(jTable1);
    }//GEN-LAST:event_prikazButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransakcijaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransakcijaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransakcijaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransakcijaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new TransakcijaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton povratakButton;
    private javax.swing.JButton prikazButton;
    private javax.swing.JButton prikazIsplate;
    private javax.swing.JButton prikazUplate;
    // End of variables declaration//GEN-END:variables
}
